### ISSUE TITLE
OmsiRemoteMethods are not initialised, remote memory allocator cannot be used!)

### ISSUE THREAD

**Issue by Burst99325** [space928/Omsi-Extensions#103]
hook.Globals.PlayerVehicle.SetStringVariable(...) causes this exception:

"One or more errors occurred. (OmsiRemoteMethods are not initialised, remote memory allocator cannot be used!)"

**Comment by space928** [comment]
I'm just copying what you found out on Discord here, to remind myself when I come back to this:

This issue is that the `OMSI_PLUGIN` is still being used in `Memory.cs`
![image](https://github.com/user-attachments/assets/f56c7e03-4d40-418b-ae0d-6ec195df25a1)

**Comment by Burst99325** [comment]
Line 1108 and 1145 in Memory.cs
