### ISSUE TITLE
Modifying string vars and removing the bus

### ISSUE THREAD

**Issue by Ixe1** [space928/Omsi-Extensions#54]
Steps taken:
- Load into a map
- Spawn a bus
- Modify one or more string vars
- Remove the bus

Outcome:
- OMSI produces an error message

**Comment by space928** [comment]
Please feel free to test out the changes proposed in #69, which implements a proper RPC system for remote memory allocation using Omsi's native memory allocator. This branch includes a new project "OmsiHookRPCPlugin" which is a plugin which NEEDS to be installed in Omsi's plugins folder for any remote methods to work:
![image](https://github.com/space928/Omsi-Extensions/assets/15130114/a68f667f-9fdb-4510-84aa-441df87dda93)

Technically this plugin is only needed when using OmsiHook outside of an Omsi plugin when doing anything that needs to allocate memory (string writing, array appending, etc...).

**Comment by space928** [comment]
Fixed in #69
