### ISSUE TITLE
Example OmsiHookPlugin doesn't function

### ISSUE THREAD

**Issue by Joost1991** [space928/Omsi-Extensions#77]
Hi devs!

Thank you for all the wonderful work you did on this!

I'm having some trouble getting the example OmsiHookPlugin working. When trying it out and building it and letting it copy it towards the plugins directory automatically, it will load OMSI but before after a few seconds it will exit OMSI again.

Nothing to see in the logs. Only thing I can see in the omsiHookPluginLog.txt it shows the example lines up until the point where it says `Didn't crash!`. In the OMSI log itself the last line there is `Initializing plugins`.

Can you confirm that the example plugin is still working properly for you?

Thanks!

**Comment by space928** [comment]
Hi, this should be resolved in the latest release. Let me know if there are any other issues.

**Comment by Joost1991** [comment]
Seems to be working now, thanks for the quick response!
